### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by hypnomez**

### CODE REVIEW

**Comment by nazar-pc** [comment]
No translation `instruktsia`

**Comment by hypnomez** [comment]
please publish only Ukrainian version

Best Regards,
Vladyslav Greziev

email: greziev.v@gmail.com mailto:greziev.v@gmail.com
phone: +38 093 01 222 11

**Comment by nazar-pc** [comment]
O_o?
There is no translation for `$L->instruktsia` in any language

**Comment by hypnomez** [comment]
check it

Best Regards,
Vladyslav Greziev

email: greziev.v@gmail.com mailto:greziev.v@gmail.com
phone: +38 093 01 222 11

**Comment by nazar-pc** [comment]
Another PR? He was supposed to be here ...

**Pull request merged**
