### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by hypnomez**

### CODE REVIEW

**Comment by nazar-pc** [comment]
Same file edited as in #9, which to accept O_o?

**Comment by hypnomez** [comment]
latest version please

Best Regards,
Vladyslav Greziev

email: greziev.v@gmail.com mailto:greziev.v@gmail.com
phone: +38 093 01 222 11

**Comment by nazar-pc** [comment]
#9 contains 2 files edited

**Comment by nazar-pc** [comment]
Applied in 4395669

**Pull request closed without merging**
